---
- name: Add Nginx PPA
  apt_repository:
    repo: "{{ nginx_ppa }}"
    update_cache: yes

- name: Install Nginx
  apt:
    name: "{{ nginx_package }}"
    state: present
    force: yes

- name: Grab h5bp/server-configs-nginx
  git:
    repo: "https://github.com/h5bp/server-configs-nginx.git"
    dest: "{{ nginx_path }}/h5bp-server-configs"
    version: 82181a672a7c26f9bc8744fead80318d8a2520b1
    force: yes

- name: Move h5bp configs
  command: cp -R {{ nginx_path }}/h5bp-server-configs/h5bp {{ nginx_path }}/h5bp
  args:
    creates: "{{ nginx_path }}/h5bp/"

- name: Create nginx.conf
  template:
    src: "{{ nginx_conf }}"
    dest: "{{ nginx_path }}/nginx.conf"
  notify: reload nginx

- name: Disable default server
  file:
    path: "{{ nginx_path }}/sites-enabled/default"
    state: absent
  notify: reload nginx

- name: Drop requests for unknown hosts
  template:
    src: "no-default.conf.j2"
    dest: "{{ nginx_path }}/sites-available/no-default"

- name: Create brookjs-realworld.io nginx config
  template:
    src: "brookjs-realworld.io.j2"
    dest: "{{ nginx_path }}/sites-available/brookjs-realworld.io.conf"
  notify: reload nginx

- name: Enable brookjs-realworld.io nginx config
  file:
    src: "{{ nginx_path }}/sites-available/brookjs-realworld.io.conf"
    dest: "{{ nginx_path }}/sites-enabled/brookjs-realworld.io.conf"
    owner: root
    group: root
    state: link
  notify: reload nginx
