---
- name: Checking essentials
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
  with_items: "{{ apt_packages }}"

- name: Validate timezone variable
  stat:
    path: /usr/share/zoneinfo/{{ ntp_timezone }}
  register: timezone_path
  changed_when: false

- name: Explain timezone error
  fail:
    msg: "{{ ntp_timezone }} is not a valid timezone. For a list of valid timezones, check https://php.net/manual/en/timezones.php"
  when: not timezone_path.stat.exists

- name: Add myhostname to nsswitch.conf to ensure resolvable hostname
  lineinfile:
    backrefs: yes
    backup: yes
    dest: /etc/nsswitch.conf
    line: \1 myhostname
    regexp: ^(hosts\:((?!myhostname).)*)$
    state: present

- name: Generate SSH key for vagrant user
  user:
    name: vagrant
    generate_ssh_key: yes
  when: env == 'development'

- name: Create web root
  file:
    path: "{{ www_root }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory

- name: Create logs folder of sites
  file:
    path: "{{ www_root }}/logs"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
